services:
  - type: web
    name: shinchoku
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_TYPE
        value: postgres
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: shinchoku-db
          property: connectionString

databases:
  - name: shinchoku-db
    plan: free